feat: add action

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,23 +1,130 @@
-name: Rename me
+name: Cross GoReleaser
 description: |
-  Template repository for creating Composite Action with GitHub Actions.
+  This action serves as a convenient wrapper for [goreleaser/goreleaser-action][goreleaser].
 
   ## Usage
 
-  Write usage for your Composite Action.
+  To set up the action, you need to create a YAML file that defines your configurations.
+  Refer to the detailed configuration syntax for the GoReleaser in [goreleaser/goreleaser-action][goreleaser].
+
+  ### Configuration URL
 
   ```yaml
     steps:
-      - name: Template
-        uses: tmknom/template-composite-action@v0
+      - name: Cross GoReleaser
+        uses: tmknom/cross-goreleaser-action@v0
+        with:
+          configuration-url: https://raw.githubusercontent.com/tmknom/configurations/main/goreleaser/cli.yml
   ```
+
+  ### Configuration Path
+
+  ```yaml
+    steps:
+      - name: Cross GoReleaser
+        uses: tmknom/cross-goreleaser-action@v0
+        with:
+          configuration-path: .goreleaser.yml
+  ```
+
+inputs:
+  configuration-url:
+    required: false
+    description: The url for the GoReleaser configurations.
+  configuration-path:
+    required: false
+    description: The path for the GoReleaser configurations.
+  dry-run:
+    default: 'false'
+    required: false
+    description: Whether to use snapshot mode when invoking GoReleaser.
+
+outputs:
+  configuration-path:
+    value: ${{ steps.config.outputs.path }}
+    description: The path for the configuration file to passing goreleaser/goreleaser-action.
+  configuration-sha256:
+    value: ${{ steps.config.outputs.sha256 }}
+    description: SHA256 of the configuration file to passing goreleaser/goreleaser-action.
 
 runs:
   using: composite
 
   steps:
-    - name: Run
-      shell: bash
+    - name: Traceable Identifier
+      id: traceable
+      uses: tmknom/traceable-identifier-action@6555160c543eb771a876fb4ceaecd43ec79df7b6 # v0.1.0
+
+    # curl options
+    #
+    # --silent: Silent or quiet mode.
+    # --silent: When used with -s, --silent, it makes curl show an error message if it fails.
+    # --location: If the server reports that the requested page has moved to a different location, redo the request on the new place.
+    # --output <file>: Write output to <file> instead of stdout.
+    - name: Download configuration
+      id: download
+      if: ${{ inputs.configuration-url != '' }}
+      env:
+        PREFIX: goreleaser
+        IDENTIFIER: ${{ steps.traceable.outputs.identifier }}
+        CONFIGURATION_URL: ${{ inputs.configuration-url }}
       run: |
+        echo "::group::Download configuration"
         set -x
-        echo "Write steps"
+        config="${RUNNER_TEMP}/${PREFIX}-${IDENTIFIER}.yml"
+        curl --silent --show-error --location --output "${config}" "${CONFIGURATION_URL}"
+        echo "path=${config}" >> "${GITHUB_OUTPUT}"
+        echo "::endgroup::"
+      shell: bash
+
+    - name: Validate configuration
+      id: config
+      env:
+        CONFIG_PATH: ${{ steps.download.outputs.path || inputs.configuration-path }}
+        DEFAULT_CONFIG_PATH: .goreleaser.yml
+      run: |
+        echo "::group::Validate configuration"
+        set -x
+        if [[ "${CONFIG_PATH}" != "" && -f "${CONFIG_PATH}" ]]; then
+          valid="${CONFIG_PATH}"
+        elif [[ -f "${DEFAULT_CONFIG_PATH}" ]]; then
+          title="configuration file was omitted"
+          message="recommend explicitly specifying the configuration file"
+          echo "::warning title=${title}::${message}"
+          valid="${DEFAULT_CONFIG_PATH}"
+        else
+          title="not found configuration file"
+          message="ensure that you specify valid configuration-path or configuration-url"
+          echo "::error title=${title}::${message}"
+          exit 1
+        fi
+        echo "path=${valid}" >> "${GITHUB_OUTPUT}"
+        echo "sha256=$(sha256sum "${valid}" | cut -d' ' -f1)" >> "${GITHUB_OUTPUT}"
+        echo "::endgroup::"
+      shell: bash
+
+    - name: Show configuration
+      env:
+        CONFIG_PATH: ${{ steps.config.outputs.path }}
+      run: |
+        echo "::group::Show configuration"
+        set -x
+        cat "${CONFIG_PATH}"
+        echo "::endgroup::"
+      shell: bash
+
+    - name: Switch dry run
+      id: dry-run
+      if: ${{ inputs.dry-run != 'false' }}
+      run: |
+        echo "args=--snapshot" >> "${GITHUB_OUTPUT}"
+      shell: bash
+
+    - name: Run GoReleaser
+      uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # v6.0.0
+      with:
+        distribution: goreleaser
+        version: ~> v2
+        args: release --clean --config ${{ steps.config.outputs.path }} ${{ steps.dry-run.outputs.args }}
+      env:
+        GITHUB_TOKEN: ${{ github.token }}
